# This is a basic workflow to help you get started with Actions

name: build  
on: push
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
      - name: testing
        run: echo testing success
        
              # zip build project
      - name: zip release for deploy
        run: zip release.zip ./* -r

      # Save workspace for other jobs
      - name: Save workspace for other jobs
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: release.zip
        
  development:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo this is deploy development
      
      - name: attach workspace
        uses: actions/download-artifact@v3
        with:
          name: release
     
      - name: list file
        run: ls -R
      # unzip project from build step
      - name: unzip build project
        run: unzip release.zip
