# This is a basic workflow to help you get started with Actions

name: build  
on: push
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
      - name: testing
        run: echo testing success
        
              # zip build project
      - name: zip release for deploy
        run: zip release.zip ./* -r

      # Save workspace for other jobs
      - name: Save workspace for other jobs
        uses: actions/upload-artifact@v3
        with:
          name: release
          path: release.zip
          
  development:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/development'
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
      - name: testing
        run: echo testing success
        
              # zip build project
      - name: zip release for deploy
        run: zip release.zip ./* -r

      # Save workspace for other jobs
      - name: attach workspace
        uses: actions/download-artifact@v3
        with:
          name: release
      # Save workspace for other jobs
      - name: list file
        run: ls -R
        
  production:
    runs-on: ubuntu-latest
    needs: [build, development]
    if: github.ref_type == 'tag' && contains(github.ref_name, 'v[0-9]+(\.[0-9]+)*')
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
    
      - name: testing
        run: echo testing success
        
              # zip build project
      - name: zip release for deploy
        run: zip release.zip ./* -r

      # Save workspace for other jobs
      - name: attach workspace
        uses: actions/download-artifact@v3
        with:
          name: release
      # Save workspace for other jobs
      - name: list file
        run: ls -R
             
