name: development
on:
  workflow_run:
    workflows:
      - build
    branches:
      - development
    types:
      - completed

jobs:
  # This workflow contains a single job called "build"
  development:
  
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo this is deploy development
      
      - name: attach workspace
        uses: actions/download-artifact@v3
        with:
          name: release
          
      - name: list file
        run: ls
