name: deploy

on:
  push:
    branches-ignore:
      - '*'

jobs:
  # This workflow contains a single job called "build"
  build-porduction:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo this is deploy build
